language: php
php:
  - '7.0'
env:
  - SYMFONY_VERSION="3.*.*"
install:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}
  - composer require satooshi/php-coveralls
before_script:
  - composer require symfony/http-foundation:${SYMFONY_VERSION}
  - mkdir -p build/logs

script:
  - phpunit --coverage-text
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'


