language: php
php:
  - '7.0'
env:
  - SYMFONY_VERSION="3.1.*"
install:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}
before_script:
  - composer require symfony/http-foundation:${SYMFONY_VERSION}

script: phpunit --coverage-text

